version: '3'

services:
  anydexgrasp:
    build:
      context: .
      dockerfile: Dockerfile
    image: anydexgrasp:latest
    container_name: anydexgrasp
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host
    stdin_open: true
    tty: true 